config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'users#index'
  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy]
    resources :posts, only: [:index, :show, :create, :new, :destroy] do
      member do
        post 'like'
        delete 'unlike'
      end
      resources :comments, only: [:new, :create, :destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/views/pages/_comments_card.html.erb
<div class="card border-2 border-dark mt-2">
  <div class="card-body">
    <% comments.each do |comment| %>
      <div class="d-flex justify-content-between w-100 border-bottom py-3 align-items-center">
        <p class="m-0"><b><%= comment.author.name %></b>: <%= comment.text %></p>
        <% unless @user.nil? || @post.nil? %>
          <%= link_to 'Delete', user_post_comment_path(user_id: @user.id, post_id: @post.id, id: comment.id), class: 'btn btn-danger', data: { turbo_method: :delete } if can? :destroy, comment %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/_like.html.erb
<%= form_with url: like_user_post_path(user_id: @current_user.id, id: @post.id), model: @like do |form| %>
  <%= form.submit "Like", class: 'btn btn-primary' %>
<% end %>

app/views/pages/_post_card.html.erb
<div class="container-fluid mt-4">
<div class="card border-2 border-dark">
  <div class="card-body">
    <h4 class="card-title"><%= post.title %></h4>
    <div class="text-truncate text-justify"><%= post.text %></div>
    <div class="d-flex justify-content-end gap-1 align-items-end">
      <p class="m-0">Comments: <%= post.comment_counter %>,</p>
      <p class="m-0">Likes: <%= post.likes_counter %></p>
    </div>
  </div>
</div>
</div>

app/views/pages/_user_card.html.erb
<div class="container-fluid mt-5">
  <div class="row">
    <div class="col-3">
      <div class="card border-2 border-dark">
        <img src="<%= user.photo %>" alt="user" style="height: 100px;"/>
      </div>
    </div>

    <div class="col-9">
      <div class="card border-2 border-dark">
        <div class="card-body">
          <div class="card-title">
            <h3 class="m-0"><b><%= user.email %></b></h3>
            <h5 class="m-0"><b><%= user.role %></b></h5>
          </div>
          <div class="d-flex h-50 justify-content-end align-items-end">
            <p class="m-0">Number of posts: <%= user.posts_counter %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>